/*Exercice 1 
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000. */
function multiple() {
  let sum = 0;
  for (let i = 1; i < 1000; i++) {
    if (i % 3 === 0 || i % 5 === 0) {
      sum += i;
    }
  }
  return sum;
}
//console.log(multiple());

/* Exercice 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

// Exercice 3 - Separate vowels and consonants from a given text
function vowelsAndConsonants(s) {
  const vowels = /[aeiou]/i,
    consonants = /[bcdfghjklmnpqrstvwxyz]/i;
  for (let letter of s) {
    if (vowels.test(letter)) {
      console.log(letter);
    }
  }
  for (let letter of s) {
    if (consonants.test(letter)) {
      console.log(letter);
    }
  }
}

//console.log(vowelsAndConsonants("javascriptloops"));

/* Exercice 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ? */

function largestPrimeF(n) {
  let primeArr = [];
  for (let i = 1; i <= n; i++) {
    if (n % i === 0) {
      primeArr.push(i);
    }
  }
  return primeArr;
}

//console.log(largestPrimeF(60));

/* Exercice 3
 A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
Find the largest palindrome made from the product of two 3-digit numbers.*/

function largestPal() {
  const pal = [];
  let e = 0,
    reverse = [];
  for (let i = 0; i <= 99; i++) {
    e = 99 * i;
    e = e.toString();
    for (let i = e.length - 1; (i = 0); i--) {
      reverse.push(i);
    }
    reverse.join("");
  }
  return reverse;
}

//console.log(largestPrimeF());
