/*Exercice 1 
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.
Find the sum of all the multiples of 3 or 5 below 1000. */
function multiple() {
  let sum = 0;
  for (let i = 1; i < 1000; i++) {
    if (i % 3 === 0 || i % 5 === 0) {
      sum += i;
    }
  }
  return sum;
}
//console.log(multiple());

/* Exercice 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

// Exercice 3 - Separate vowels and consonants from a given text
function vowelsAndConsonants(s) {
  const vowels = /[aeiou]/i,
    consonants = /[bcdfghjklmnpqrstvwxyz]/i;
  for (let letter of s) {
    if (vowels.test(letter)) {
      console.log(letter);
    }
  }
  for (let letter of s) {
    if (consonants.test(letter)) {
      console.log(letter);
    }
  }
}

//console.log(vowelsAndConsonants("javascriptloops"));

/* Exercice 3
The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ? */

function largestPrimeF(n) {
  let factorArr = [];
  for (let i = 0; i <= n; i++) {
    if (n % i === 0) {
      if (i % 1 === 0) {
      }
    }
  }
  return factorArr;
}

console.log(largestPrimeF(600));
